### ISSUE TITLE
Improve code structure

### ISSUE THREAD

**Issue by pando85** [RyanNoelk/OpenEats#119]
I finally decide to fork qgriffith repo and dockerize it better than repair this mess. If it can help you is [here](https://github.com/pando85/openeats).

**Comment by hermzz** [comment]
Is there a reason you're doing it off the qgriffith repo rather than this one? There's not much from your branch that we can use, we already have docker support and there's work being done on improving it #83 (although I'm not sure what the progress is on that).

**Comment by RyanNoelk** [comment]
The actual code in the api and node apps, IMO, aren't too bad. As @hermzz said, we are using docker and have a PR and tickets open to improve infrastructure.

I'm going to close this for now. Please reopen this if you want to explain more about how you think the code can be improved. If you have some specifics of things that you feel can be improved, then please open a separate issue about it and we can discuss it.
