### ISSUE TITLE
About page and credits

### ISSUE THREAD

**Issue by hermzz** [RyanNoelk/OpenEats#122]
Two part discussion: 

1. I'm not sure the about page makes any sense any more. At the very least I'd make the content DB driven, but I'd opt to just remove it entirely. 
2. Footer credits could probably be moved or reference something more relevant like a link to the github repo page and possibly a `CONTRIBUTORS` file (See [go/CONTRIBUTORS](https://github.com/golang/go/blob/master/CONTRIBUTORS) or [gcc/MAINTAINERS](https://github.com/gcc-mirror/gcc/blob/master/MAINTAINERS)) or the [Contributors tab](https://github.com/RyanNoelk/OpenEats/graphs/contributors).

**Comment by RyanNoelk** [comment]
I agree with dropping the about page. It doesn't add anything at this point. I also agree with your second point, it should just be a link to the github page.

**Comment by RyanNoelk** [comment]
I spun off the Contributors file into another ticket. Feel free to take it from me if you like.
