### ISSUE TITLE
Ingredient sections

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#125]
Some recipes I have, in some ways, two recipes. See this recipe for an example: https://www.budgetbytes.com/2016/12/vegetable-pot-pie-skillet-cheddar-biscuit-topping/

We should consider having support for sub-headers in the Ingredient sections, similar to below:
![screen shot 2017-02-15 at 9 17 07 am](https://cloud.githubusercontent.com/assets/11916338/22978152/8c4d9d3e-f35f-11e6-943c-3e181a709c5f.png)

**Comment by rustymyers** [comment]
There are many recipes that utilize these styles, such as a frosting for a cake, sauce for steak, or salsa for Taco Tuesdays. I would suggest that it deserves more than just a subheading, although I don't disagree that subheadings are a solution.  I would also suggest having an ability to link other recipes as "supportive" recipes. 

Supporting subheadings allows for minor recipes that are required for the main recipe, but do not allow them to function alone or to be shared with other recipes. Instead, by linking to other recipes, it provides the ability to share them across multiple parent recipes and have them as stand-alone from the main recipe. Does this make sense for all recipes? No, definitely not. Might I want those Cheddar Biscuits for breakfast? I think so.

**Comment by RyanNoelk** [comment]
As you said above, both features would be helpful. Whoever takes up this ticket should taking that into consideration when building this.

**Comment by RyanNoelk** [comment]
Fixed with #224
