### ISSUE TITLE
Firefox breaks in we don't set the Accept header to json

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#143]
See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation/List_of_default_Accept_values

So there are a few ways that we can fix this:
1. Warp all get calls that superagent does to set the header.
2. Force Django Rest to only return json.
3. Specify `format=json` in all requests.

I have a PR to apply the third option #142. But the more work we do on this app the less I like this approach. 

The first approach is probably the most flexible, but I'm not sure how easy it would be to implement, or how efficient it would be. The second option should probable be set by default when in production. We also might be able to get by with removing it from dev as well. I know Chrome has some plugins that allow pretty json printing.

@hermzz thoughts?

**Comment by hermzz** [comment]
Yeah, I've been thinking about doing 1) but haven't figured out a good way to do so with all the ajax calls spread out in the code. I figure once we migrate everything to the Api.js file we can do something about it. The other option is to go and manually make all the requests set the header for the time being.

**Comment by RyanNoelk** [comment]
Think I found a pretty good way to handle this: https://www.npmjs.com/package/superagent-defaults

I tested it out a it worked well. We can add a bunch of defaults to it and keep the code DRY.

**Comment by hermzz** [comment]
Yes, that's perfect!

**Comment by RyanNoelk** [comment]
Fixed with #145
