### ISSUE TITLE
Create a django like admin interface in react

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#160]
We don't need many of the features that the admin panel has, just the following:
- CRUD operations on users.
- CURD operations on courses.
- CURD operations on cuisines.

This will also prevent the API from serving static.

**Comment by OmgImAlexis** [comment]
I'd also suggest looking into vuejs as it's a lot easier to learn and has just as much support for plugins and tutorials, etc.

**Comment by RyanNoelk** [comment]
The whole UI right now is built with react. I'm not 100% convinced about using vuejs when everything else in in react. Maybe there is a simple way to link the two together but I would prefer if we stuck with react.

**Comment by OmgImAlexis** [comment]
Oh I haven't looked through the UI section so ignore that.
