### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by chaosblog** [RyanNoelk/OpenEats#168]
Is there a way to change the ui-language via the frontend?

**Comment by RyanNoelk** [comment]
Not at the moment. It's all controlled via the environment variable `NODE_LOCALE`. Where the options are as follows:
- English = `en`
- Spanish = `es`
- German = `de`

Though this is something that I do want to add at some point.

**Comment by hermzz** [comment]
I have a vague recollection of looking at how to do it a while ago, but it was either really complicated or not possible without upgrading webpack and/or react. Considering our use case (small communities) all content will be in one fixed language so there's not a huge value in being able to change locale on the fly.

**Comment by RyanNoelk** [comment]
I agree with the above. If someone whats to submit a PR, I'm all for it. However I don't think that I will work on this any time soon.
