### ISSUE TITLE
filter does not work completely (correct)

### ISSUE THREAD

**Issue by DJCrashdummy** [RyanNoelk/OpenEats#194]
i had a look at https://food.ryannoelk.com and played a little bit around... _(btw some of the recipes look/sound really delicious!)_
then i noticed when typing more than one - also common - ingredient, hardly anything is listed. i know it is not a huge collection but also when typing 2 ingredients which are definitely included, the recipe doesn't get listed!

either this is a bug or it has to do with something how the recipes are created...?

_btw: are there different "classifications" of ingredients like "main" and "additional" or "supportive"? - maybe that's why some ingredients aren't considered and it's recipe isn't listed? - if not, maybe as an option this is an interesting feature..._

**Comment by RyanNoelk** [comment]
Yes, I recently noticed this as well. The search box will filter just fine by title for example. But searching my ingredients isn't working. I'll work on a fix soon.

**Comment by RyanNoelk** [comment]
This should be resolved now.
