### ISSUE TITLE
better navigation & management for (complete) recipe-list

### ISSUE THREAD

**Issue by DJCrashdummy** [RyanNoelk/OpenEats#195]
- [ ] usually the view is limited to 12 recipes and you can just click older (or newer), but there is no way to go to the first/last site with one click or even to one particular in between.

- [ ] and when you start browsing with the normal view (or use the text-filter), you have no clue how much recipes/sites you can browse.

- [ ] an option for different sortieing (like mentioned @ https://github.com/RyanNoelk/OpenEats/issues/195#issuecomment-318370346) would be nice.

**Comment by DJCrashdummy** [comment]
> and when you start browsing with the normal view, you have no clue how much recipes/sites you can browse.

this also occurs when you use the text-filter.

maybe just add to the left or right of the text-filter a counter like `recipes_filtered/total_recipes`, or just the `recipes_filtered`, since at the beginning the both numbers are equal.

**Comment by DJCrashdummy** [comment]
additionally the ability (at least for the admin) to sort the recipes not just by date _(is it the creation or the last edit?)_ may be a nice feature. thinking of some options like sorting by:
- creation date
- last edit
- rating
- difficulty level (when implemented)
- time consumption (overall)
- alphabetically

**Comment by RyanNoelk** [comment]
closing this in favor of https://github.com/RyanNoelk/OpenEats/issues/287
