### ISSUE TITLE
does not work with firefox on android

### ISSUE THREAD

**Issue by DJCrashdummy** [RyanNoelk/OpenEats#197]
just tested with https://food.ryannoelk.com/, but if you open it (or any recipe) with firefox on android only an empty white site is displayed.

_PS: i'll try to gather more information this weekend._

**Comment by RyanNoelk** [comment]
Hmm , your right. I've always used Chrome, but for whatever reason its not working on Firefox.

**Comment by RyanNoelk** [comment]
This looks like an issue with the react-intl: https://github.com/yahoo/react-intl/wiki#i18n-in-javascript

Will need to use a poly fill to fix it.

**Comment by DJCrashdummy** [comment]
now it got a little bit strange:
since it isn't working on any device with firefox (wether it is 45esr or the latest 54), i tested with the internal android-webiew (not chrome) and...
- on a tablet with android 5.1.1 it works as it should,
- but on a phone with cyanogenmod 12.1 (which is also based on android 5.1.1) it does not.

of course i'm talking about firefox for android! - on desktops, wether it is windows or linux, firefox is working well.

**Comment by RyanNoelk** [comment]
I'm working on adding the Poly-fill that is needed for the mobile browsers now. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Browser_Compatibility

**Comment by RyanNoelk** [comment]
Fixed with #218
