### ISSUE TITLE
front end not talking to api on different hostname

### ISSUE THREAD

**Issue by rustymyers** [RyanNoelk/OpenEats#201]
Trying to set up the dev environment and ./manage.py createsuperuser seems to complete, but I'm unable to log into the site. How can I get a user created to log into the site?

**Comment by RyanNoelk** [comment]
Have you tried logging into the admin panel/API directly? - http://localhost:8000/admin/ or http://localhost:8000/api/v1/recipe/

I just checked out the latest version of dev and I'm not having any issues.

**Comment by rustymyers** [comment]
Thanks, that helps. I wasn't aware of the difference between the api and frontend. How do I create users for front end, then? I tried adding another using in the admin panel, selecting it as staff, but it didn't work from the frontend.

**Comment by RyanNoelk** [comment]
The users for the frontend and the backend are the same. But I wasn't sure if there was a problem creating a user or not.

Do you mind giving me a print screen of the console errors that you are getting when trying to login via the frontend. There should be something there, as this is most defiantly a connectivity issue with the frontend and the backend.

**Comment by rustymyers** [comment]
Sure, but would you mind explaining where I'd see those console errors? I'm guessing I need to look at the logs for the node docker?

**Comment by RyanNoelk** [comment]
you'll need to open the dev tools in the browser: https://developers.google.com/web/tools/chrome-devtools/shortcuts

Then navigate to the console:
<img width="1220" alt="screen shot 2017-07-03 at 2 44 45 pm" src="https://user-images.githubusercontent.com/11916338/27804679-3b3ce984-5ffe-11e7-89cb-0f3ad03b2c62.png">

**Comment by rustymyers** [comment]
Thanks! Appears to be this issue: 

`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.0.1.10:8080' is therefore not allowed access.`

[Image](https://psu.box.com/s/krv26odl1nfywdhk9ux7wix29bwna2uh)

**Comment by rustymyers** [comment]
Ok, I figured it out. I feel dumb. :)
Turns out it was because I was accessing the frontend on 10.0.1.10 and the api was on localhost. That mismatch caused the it to fail to connect. It's my tendancy to use 127.0.0.1 instead of localhost that screwed me. I'm working now, thanks!

**Comment by RyanNoelk** [comment]
You need to make sure that you set the NODE_URL to the correct URL that the frontend is being served from: 

https://github.com/RyanNoelk/OpenEats/blob/master/api/base/settings.py#L162-L164
https://github.com/RyanNoelk/OpenEats/blob/master/env_dev.list#L20

You can change this in the settings.py file or update your ENV file to include the correct URL.

**Comment by rustymyers** [comment]
Thanks again for the help!
Just for the record, after I made the change I updated the docker image with:
`docker-compose build
docker-compose up -d`
