### ISSUE TITLE
please make it possible to apply more than one filter of a kind

### ISSUE THREAD

**Issue by DJCrashdummy** [RyanNoelk/OpenEats#207]
for example you desire "some asian dish", but you don't care if it is Chinese, Japaneses, Thai or maybe also Indian; you should be able to simply check them all and don't have to go through them one by one... even multiple times if you want to apply filters of an other kind.
_--> especially for small recipe-collections this may be meaningful._

this is just one example, but i don't see why this shouldn't also be possible for the other kinds of filters.

**Comment by RyanNoelk** [comment]
closing this in favor of https://github.com/RyanNoelk/OpenEats/issues/287
