### ISSUE TITLE
little layout-improvements

### ISSUE THREAD

**Issue by DJCrashdummy** [RyanNoelk/OpenEats#212]
first i didn't want to mention it, since they are just a little - maybe personal - preference... but at least with #206 it got a little bit serious:

**i don't get it why the servings have to be the farthest away from the ingredients...?**

- [ ] for me the servings correlates with the ingredients and in conjunction with the "big solution" for #193 moving them there would be the best solution.
--> this will also release some space, maybe for moving the difficulty level https://github.com/RyanNoelk/OpenEats/issues/206#issuecomment-314058324 beside the times...

- [x] but for a quick and easy improvement please at least invert the order in the table, since the servings next to the ingredients would be better, then the next step is the preparation and the last is cooking.

**Comment by RyanNoelk** [comment]
This makes a ton of since. I'm defiantly not a UX expert, so I welcome any changes like this.

**Comment by DJCrashdummy** [comment]
as you see i tried the quick improvement myself, but sadly i have no idea of GUI development and i'm neither an expert... :disappointed:

**Comment by RyanNoelk** [comment]
Fixed with #214
