### ISSUE TITLE
Edit recipe does not auto populate fields 

### ISSUE THREAD

**Issue by rustymyers** [RyanNoelk/OpenEats#222]
Here's a fun one, when I hit edit on a recipe, all fields are empty. What did I break?

**Comment by rustymyers** [comment]
Well, not sure what happened. It's working now. Nevermind!

**Comment by RyanNoelk** [comment]
Hey, If it happens again, open up the dev console and let me know if there where any errors. :)

**Comment by rustymyers** [comment]
Thanks. I was on iOS when the problem occurred. I don't know if there's a console there?

**Comment by RyanNoelk** [comment]
I'm an Android guy, so I'm not sure :P
