### ISSUE TITLE
the "last edit"-date is missing

### ISSUE THREAD

**Issue by DJCrashdummy** [RyanNoelk/OpenEats#230]
the filters work perfect, but now the date in the content-footer is missing.

I'm not sure whether it has to do with #215, #221 or something different, but a completely unqualified guess from my side in that maybe this block needs a rework:
https://github.com/RyanNoelk/OpenEats/blob/master/frontend/modules/recipe/components/RecipeScheme.js#L179-L183

**Comment by RyanNoelk** [comment]
The API is no longer returning date information about the recipes; even though the database has the data. I'm taking a look.

**Comment by RyanNoelk** [comment]
This be fixed now.
