### ISSUE TITLE
No course or quisine selectable when adding a new recipe

### ISSUE THREAD

**Issue by bulburDE** [RyanNoelk/OpenEats#234]
After setting up OpenEats with docker and running the first time setup scripts, when creating a new recipe, no courses and no cuisines are selectable. Since those fields are mandatory, I cannot create a new recipe.
In the admin panel the entries exist.

After executing the scripts to add test data I can select course=Entry and cuisine=American, which are the entries used in the example data.

The api calls ( .../api/v1/recipe_groups/course/ and .../api/v1/recipe_groups/cuisine/ ) are also just showing those entries.

Did I miss a step to activate the entries?

**Comment by RyanNoelk** [comment]
You're right. I was re-using the same end-point that automatically does the filtering for the browse page. So if a recipe doesn't have that courses or cuisines. It won't show on the recipe page. Working on a fix now.

**Comment by RyanNoelk** [comment]
I added I fix for this. a new image will be available in about in hour. Let me know if it is still giving you trouble.

**Comment by RyanNoelk** [comment]
FYI, I found another issue with creating recipes. you'll want to download the latest images when you get a chance.

**Comment by bulburDE** [comment]
I can confirm that the courses and cuisines are now selectable. Thanks for the quick fix.
