### ISSUE TITLE
Update German translations

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#236]
The translation files are getting pretty stale at this point. We should update them.

**Comment by DJCrashdummy** [comment]
well... i'm in for german, but from my point of view the (most) translations are still ok.
maybe the one or other polish can be done, but it isn't a big issue... i'll take a look at it in the next weeks.

**Comment by RyanNoelk** [comment]
I added a few new strings to the UI that I haven't updated in the translations files yet.

**Comment by RyanNoelk** [comment]
PR for i18n can be found here https://github.com/RyanNoelk/OpenEats/pull/254

**Comment by RyanNoelk** [comment]
Fixed with #254
