### ISSUE TITLE
Update Spanish Translations 

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#237]
The translation files are getting pretty stale at this point. We should update them.

**Comment by bglopez** [comment]
Added PR #253 -- there wasn't much to do to fix it, but if there are new phrases that need adding let me know.

**Comment by RyanNoelk** [comment]
PR for translations can be found here: https://github.com/RyanNoelk/OpenEats/pull/254

**Comment by DJCrashdummy** [comment]
i just want to mention, that the punctuation in line 36, 44, 46 and 47 got lost in translation... and in line 36 there is also an unnecessary space at the end.

**Comment by RyanNoelk** [comment]
Fixed with #254
