### ISSUE TITLE
Cannot delete recipe

### ISSUE THREAD

**Issue by bulburDE** [RyanNoelk/OpenEats#252]
When deleting a recipe in the django administration panel the following error is shown:

`TypeError at /admin/recipe/recipe/ `
`coercing to Unicode: need string or buffer, NoneType found`

[detailed error log](https://github.com/RyanNoelk/OpenEats/files/1262031/deletion_error.txt)

The recipe still exists afterwards. I tried it with various recipes and got the error with each one of them.

**Comment by RyanNoelk** [comment]
The admin panel is mostly isolated for the rest of the site. It uses the stock django admin panel to render all the data/operations.

With that been said, it looks like there is some data that is just missing, most likely the title. The title is required in most models and if its not present, will cause issues. Are you able to update the recipe to confirm that all data is accounted for?

**Comment by bulburDE** [comment]
The deletion is failing whenever a recipe has an ingredient without an ingredient group. In the recipe serializer. In the RecipeSerializer the statement
```python 
group = IngredientGroup.objects.create(
     recipe=instance, title=ingredient_group.get('title')
)
```
returns `Unable to get repr for <class 'v1.ingredient.models.IngredientGroup'>` because title is `None`. If I change `title=ingredient_group.get('title')` to `title=ingredient_group.get('title', "Default")`, the error doesn't occur.

Besides the error when deleting a recipe, I found some other errors that seem related to this. Ingredient groups without a title can not be edited in the admin panel because an error occurs:
[admin_ingredient_group.txt](https://github.com/RyanNoelk/OpenEats/files/1275637/admin_ingredient_group.txt)
Editing any ingredient also throws an error:
[admin_ingredient.txt](https://github.com/RyanNoelk/OpenEats/files/1275639/admin_ingredient.txt) This occurs in every case I tested, independent from the IngredientGroup.

**Comment by RyanNoelk** [comment]
I'll take a look and have a pull request up  in the next day or so.

**Comment by RyanNoelk** [comment]
So the issue with the admin page and deletion should be mostly resolved with the PR above.

**Comment by RyanNoelk** [comment]
The issues with the admin panel should be fixed. The admin panel was trying to using the title of each model and that was causing some issues.

Please reopen if you continue to have issues.
