### ISSUE TITLE
some new languages required?

### ISSUE THREAD

**Issue by DJCrashdummy** [RyanNoelk/OpenEats#261]
i just wanted to ask how much new languages are desired, if at all?

and if yes, is there a priority list? ...or has somebody one in mind?

**Comment by RyanNoelk** [comment]
I think #254 has all the translations that are going to be needed for now. I just had been focusing on adding new features; I didn't get a chance to keep up with the translation files.

**Comment by DJCrashdummy** [comment]
@RyanNoelk sorry for not being precise enough.

**Comment by RyanNoelk** [comment]
Ahh, well anyone is more than welcome to add any languages that this wish the site to support. The one warning I will give anyone adding languages is that I only speak English fluently. There might be some delay before other languages get a proper translation update. I will also try and add new translations via Google translate as an interim solution.

**Comment by RyanNoelk** [comment]
Closing this. If you want more information on how to add new langs, please reopen.

In any case, the translation json will be the same as the other langs regardless.
