### ISSUE TITLE
Docker Installation instructions incomplete.

### ISSUE THREAD

**Issue by daniel-widrick** [RyanNoelk/OpenEats#308]
When following the docker installation instructions for a prod environment the following error is gven after running the "docker-compose run --rm --entrypoint 'python manage.py createsuperuser' api" command produces the following error:

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by RyanNoelk** [comment]
There was a error in the docs. It was missing the reference to the compose config

try:
 ``` bash
 docker-compose -f docker-prod.yml run --rm --entrypoint 'python manage.py createsuperuser' api
  ```
See: https://github.com/RyanNoelk/OpenEats/pull/310 for the correction

**Comment by RyanNoelk** [comment]
Please reopen if the above isn't working :)
