### ISSUE TITLE
API port not externally visible under docker for MacOS

### ISSUE THREAD

**Issue by gurudave** [RyanNoelk/OpenEats#315]
It seems that docker for MacOS doesn't create a bridged network interface, so the port binding used by the API isn't externally visible, and therefore you can't login, etc...

This is fixable by adding a port mapping to the docker-prod.yml file in the api section, in the same way for nginx:

```
services:
  api:
    ports:
    - "8079:8079"
```

In this case 8079 is the port I specified in my env configuration.

I'm not familiar enough with docker to know how this should be properly incorporated into the files in your repo, otherwise I'd open a PR. I'm happy to provide more info if you need it though!

**Comment by RyanNoelk** [comment]
The production version of the docker compose file is specificity not exposing the ports. There is a nginx server that sits in front of the api/UI and makes sure to redirect the urls appropriately. The apis are accessible via: `my.domain.com/api`

See: https://github.com/RyanNoelk/OpenEats/blob/master/services/default.conf#L21

The dev version exposes the ports as you said above: https://github.com/RyanNoelk/OpenEats/blob/master/docker-compose.yml#L14

Going to close this issue. Though it you have more questions feel free to ask. :)
