### ISSUE TITLE
openeats_db_1 docker won't start

### ISSUE THREAD

**Issue by rustymyers** [RyanNoelk/OpenEats#330]
I probably broke this doing something, but I can't figure out what. openeats_db_1 isn't starting and gives me this in the log:

> 2018-02-06  1:42:54 139732552107968 [Note] mysqld (mysqld 10.1.24-MariaDB-1~jessie) starting as process 1 ...
2018-02-06  1:42:55 139732552107968 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2018-02-06  1:42:55 139732552107968 [Note] InnoDB: The InnoDB memory heap is disabled
2018-02-06  1:42:55 139732552107968 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2018-02-06  1:42:55 139732552107968 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2018-02-06  1:42:55 139732552107968 [Note] InnoDB: Compressed tables use zlib 1.2.8
2018-02-06  1:42:55 139732552107968 [Note] InnoDB: Using Linux native AIO
2018-02-06  1:42:55 139732552107968 [Note] InnoDB: Using SSE crc32 instructions
2018-02-06  1:42:55 139732552107968 [ERROR] mysqld: Can't create/write to file '/tmp/ib8J5Owh' (Errcode: 13 "Permission denied")
2018-02-06 01:42:55 7f160521c7c0  InnoDB: Error: unable to create temporary file; errno: 13
2018-02-06  1:42:55 139732552107968 [ERROR] Plugin 'InnoDB' init function returned error.
2018-02-06  1:42:55 139732552107968 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
2018-02-06  1:42:55 139732552107968 [Note] Plugin 'FEEDBACK' is disabled.
2018-02-06  1:42:55 139732552107968 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
2018-02-06  1:42:55 139732552107968 [ERROR] Unknown/unsupported storage engine: InnoDB
2018-02-06  1:42:55 139732552107968 [ERROR] Aborting

The other containers seem to be running fine, so I'm not sure what's up. /tmp seems to have the correct permissions on the local filesystem, but I think this must be something with the container?

To troubleshoot I stopped and started all the containers with docker compose up -d. Initially the node container also didn't come back up. I then did a git pull to get the latest changes and ran 

> docker-compose -f docker-compose.yml up -d
docker-compose build
docker-compose up -d

After that I got the node and api running, but the mariadb container still has the same error. Any thoughts on what I did wrong? Was thinking about blowing it all away and starting over, but don't want to lose my recipes either.
Thanks

**Comment by RyanNoelk** [comment]
hmm that's weird. I've never seen that error before. Before you go any farther I would recommend taking a backup of your db.

First try and start the container with: `dc run --rm --entrypoint=bash db`. This should just open up a bash shell to your database.

Once that is up and running you can follow the steps [here](https://github.com/RyanNoelk/OpenEats/blob/master/docs/Taking_Backups.md) to take backups.

Be sure to replace the container names with the names of your containers. You can get the names by running `docker ps`.

If that all runs successfully (make sure to double check the sql file to confirm it has all the first data), you many just have to blow off the DB. Though u can try running `docker-compose -f docker-prod.yml down` and then trying to boot the containers back up.

Let me know how it goes!

**Comment by rustymyers** [comment]
Ok, so here's my docker ps -a

>  docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                         PORTS                    NAMES
9847c14a677d        openeats_node       "npm start"              About an hour ago   Up About an hour               0.0.0.0:8080->8080/tcp   openeats_node_1
dd0a5d904469        openeats_api        "python manage.py ..."   About an hour ago   Up About an hour               0.0.0.0:8000->8000/tcp   openeats_api_1
70336fd66f47        mariadb             "docker-entrypoint..."   About an hour ago   Exited (1) About an hour ago                            openeats_db_1

docker run gives me another weird error.
> docker run --rm --entrypoint=bash openeats_db_1
Unable to find image 'openeats_db_1:latest' locally
docker: Error response from daemon: repository openeats_db_1 not found: does not exist or no pull access.
See 'docker run --help'.

I noticed I wasn't on the latest commits for the dev branch, so I pulled those changes and tried to compose again. Same error with mariadb not being able to write to /tmp.

**Comment by RyanNoelk** [comment]
Sorry I was using my alias for docker-compose. Try `docker-compose run --rm --entrypoint=bash db` from where ever your docker compose files live.

**Comment by rustymyers** [comment]
Ok, that works. I should have figured dc was docker-compose and not docker.

Now trying to dump the mysql database, but it says the container isn't running.
> docker exec openeats_db_1 sh -c 'exec mysqldump openeats -uroot -p"$MYSQL_ROOT_PASSWORD"' > openeats.sql
Error response from daemon: Container c3778066dea4a20a2892550f4018f7414940b99320ef3543d4f24012d05ecf01 is not running

Running the mysqldump from within the container gives me
> root@f0f01ea82f25:/# exec mysqldump openeats -uroot -p"$MYSQL_ROOT_PASSWORD"
mysqldump: Got error: 2002: "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")" when trying to connect

Trying to run the command from outside the container against the running db
>CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                    PORTS                    NAMES
3b7085cc06a4        mariadb             "bash"                   2 minutes ago       Up 2 minutes              3306/tcp                 openeats_db_run_1
ae26d532699d        openeats_node       "npm start"              9 hours ago         Up 9 hours                0.0.0.0:8080->8080/tcp   openeats_node_1
4f3e92b70156        openeats_api        "python manage.py ..."   9 hours ago         Up 9 hours                0.0.0.0:8000->8000/tcp   openeats_api_1
c3778066dea4        mariadb             "docker-entrypoint..."   10 hours ago        Exited (1) 10 hours ago                            openeats_db_1

Gives the same error
> docker exec openeats_db_run_1 sh -c 'exec mysqldump openeats -uroot -p"$MYSQL_ROOT_PASSWORD"' > openeats.sql
mysqldump: Got error: 2002: "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")" when trying to connect

Seems like the container is pretty busted at the moment and might time to nuke and pave. I looked at the directories inside the container that should contain the database and its empty.
>  ls -lR var/lib/mysql/
var/lib/mysql/:
total 18
-rw-rw---- 1 mysql mysql 16384 Feb  6 03:21 aria_log.00000001
-rw-rw---- 1 mysql mysql    52 Feb  6 03:21 aria_log_control
drwx------ 2 mysql mysql     2 Feb  6 01:05 mysql
> var/lib/mysql/mysql:
total 0

Anything else I should try before I try to start from scratch? Thanks for the help!

**Comment by RyanNoelk** [comment]
There are a few things.

First do a `docker volume ls`. The database lives on a volume. This will show you all your current and old volumes. It looks like the volume for your db got marked as old.

```bash
ryan@ryans-linux:~$ docker volume ls
DRIVER              VOLUME NAME
local               292730960b1cb36b0f9673255fcfb2511f1e4afa63f0b24b9590625f4c9da5e3
local               4916c6e210660650b97c8ce0dcdc78c3c5cc23a3185fcc58ddc2d198d11e7c85
local               4fecbc771d6953cbc5380ea543128bb0d35ed86f626356392e7530cf112c6cd0
```

From here you need to play the guessing game as docker doesn't give you much info on the volumes. One by one mount these volumes to a random container and see if any of them hold your database. In the below example I'm mounting the volume to `/var/lib/mysql`.

```bash
docker run -it --rm --name db_recovery_1 --entrypoint bash --mount source=4916c6e210660650b97c8ce0dcdc78c3c5cc23a3185fcc58ddc2d198d11e7c85,target=/var/lib/mysql mariadb:latest

cd /var/lib/mysql
ls
```

Be sure to keep a note of the original volumes that you had as running the above command many create new volumes then orphan then when you exit the shell. Once you find the right one, you should be able to start mysql and take a backup.

**Comment by rustymyers** [comment]
This is what I have for volumes.

```
 docker volume ls
DRIVER              VOLUME NAME
local               6263df65cdd1cd15d0d7f4663ccd9f543269279b35d76e425ace5ca19988a206
local               openeats_database
local               openeats_node_modules
local               openeats_site-media
local               openeats_static-files
```
I've checked the 6263... volume and it's empty at /var/lib/mysql. The openeats_database volume has the same contents as my previous post. It looks like it may have been removed at some point. I ran out of disk space due to docker and did some "clean up" to remove old stuff. I then moved the docker folder to another volume so it wasn't taking up my boot drive space. 

Thanks for the help, but I think my only option right now is to remove the cruft and start fresh. I think I can re-import all the recipes with a little bit of scripting as I have an API json dump from December.

**Comment by RyanNoelk** [comment]
Unfortunately that appears to be the case :(

For future reference, you can follow the steps [here](https://github.com/RyanNoelk/OpenEats/blob/master/docs/Taking_Backups.md) to take backups.

I'll also be sure to make some docs on this thread and ways to recover if container start acting funky. 

Feel free to close this issue if you don't have any more questions.

**Comment by rustymyers** [comment]
Thanks for the assistance! Just wiped out the old repo and I'm cloning the new repo now for a fresh start.

**Comment by RyanNoelk** [comment]
Let me know how it goes! (https://github.com/open-eats/OpenEats)

I've been trying to make the whole process easier. If you run into any issues at all please contact me/open an issue!

**Comment by rustymyers** [comment]
In case anyone else finds this, I think my mistake was [using cp instead of rsync when moving my docker root folder to an external drive](https://stackoverflow.com/questions/25922882/php-docker-script-unable-to-write-to-tmp)

> The sticky bit wasn't set properly in my case as well, nor the umask. Started happening after I blindly ran a [cp] instead of [rsync] (with perms) to move the docker data directory to a new (larger) hard drive
