### ISSUE TITLE
Working grocery list

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#49]
This fork does not have a any code to support grocery lists.

**Comment by RyanNoelk** [comment]
Going to use this Issue to talk about design of the Grocery list. IMO this very much resembles a TODO list, there are many demos out there for react. Heres one example that I liked:
- Demo - http://todomvc.com/examples/react/#/
- Source - https://github.com/tastejs/todomvc/tree/gh-pages/examples/react

So my overall plan for this feature has three parts in order of priority:
- Viewing and editing a grocery list.
- Creating, deleting, and sharing grocery lists.
- Adding recipe ingredients to a list.

Viewing and editing the list is pretty much taken care of in the code listed above. I would add some Flux code to incorporate the database into the list and rename the relevant things as well.

For creating, deleting, and sharing, I was thinking about adding a side bar (similar to the mini-browse for the recipe page) to hold the related recipes and the actions to create and delete them.

Logged-in users would get a button on the recipe page that allows them to add all the ingredients to the list. I'm still not 100% sure how I want this to work. going to focus on the first two items first and go from there. 

Thoughts @hermzz

**Comment by hermzz** [comment]
All sounds pretty reasonable. Hardest bit will probably be sharing. I'd be inclined to make lists public so that if you want to share the list you can just share the link, without all the complicated auth issues.

**Comment by RyanNoelk** [comment]
Yea, I'm not sure how exactly I want the sharing to work quite yet. In any case we wouldn't need that right away. I've been tinkering around with the styles and a sample below.

The one below is something that I'm looking to implement at first. Just a simple list view.

![screen shot 2017-01-30 at 10 58 27 pm](https://cloud.githubusercontent.com/assets/11916338/22451823/a6c2b4fa-e73f-11e6-9dab-e4cb5750cd1e.png)

Here is a mock of what I'm thinking it would look like Once I have multiple list support and sharing

![screen shot 2017-01-30 at 10 55 09 pm](https://cloud.githubusercontent.com/assets/11916338/22451783/423aadc6-e73f-11e6-9e63-dc5898219091.png)
