### ISSUE TITLE
Docker build for Production

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#51]
I would like to be able to run docker in production.

**Comment by OmgImAlexis** [comment]
You still have `debug = True` for the API in production.

**Comment by RyanNoelk** [comment]
Good catch. There is an env var that should be setting this. I'll take a look.

**Comment by RyanNoelk** [comment]
Fixed with #67. When python evaluates a string to a bool value. The actual value doesn't matter, as long as there is something True will always be returned. Aka bool('False') == True.
