### ISSUE TITLE
Swap npm for yarn

### ISSUE THREAD

**Issue by OmgImAlexis** [RyanNoelk/OpenEats#59]
Maybe look into switching from npm to yarn to speed up the build process?

For example on a repo that takes 2 minutes to `npm install` it only takes me around 2 seconds with `yarn install`.

**Comment by OmgImAlexis** [comment]
Here's an example of how to switch the frontend to use yarn.

```diff
diff --git a/frontend/Dockerfile b/frontend/Dockerfile
index 04affb1..a711461 100644
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -4,6 +4,9 @@ FROM node:argon
 RUN mkdir /code
 WORKDIR /code
 
+# Install yarn
+RUN curl -o- -L https://yarnpkg.com/install.sh | bash
+
 # Install app dependencies
 ADD . /code/
-RUN npm install
\ No newline at end of file
+RUN $HOME/.yarn/bin/yarn install --pure-lockfile
```

**Comment by RyanNoelk** [comment]
I welcome any PRs If this is going to achieve the same as NPM but in a fraction of the time.
