### ISSUE TITLE
Production shouldn't expose ports

### ISSUE THREAD

**Issue by OmgImAlexis** [RyanNoelk/OpenEats#62]
In the production env only the nginx container should expose ports and the frontend should be using the nginx box to connect to the api either on another port or via a subdomain.

I'd personally rather see caddy support over nginx since it does allow for easy CORS support as well as auto issuing os let's encrypt SSL certs or self signed certs without the user needing to do anything.

**Comment by RyanNoelk** [comment]
Auto issuing certs sounds pretty good. My skills using docker is production is limited. I would love any help/recommendations you have.

**Comment by OmgImAlexis** [comment]
Working on this right now.

**Comment by OmgImAlexis** [comment]
So I'm working on adding Caddy support as well as cleaning up the whole docker compose situation right now.

The thing I'm stuck on is when I run everything I don't end up with anything but text showing for the React frontend and I'm not sure what is meant inside of the following directories.
```
static-files
site-media
```

**Comment by RyanNoelk** [comment]
So the static-files and site-media are for Django and Nginx to be able to talk with each other. Since I'm using Gunicorn to serve the python inside its container, I wanted nginx to serve the static content. 
- Static-files are where 3rd party css/js are store for Django admin panel and the Django rest GUI.
- Site-media is where there images for the recipes are stored. 

I use bootstrap's CDN for most of the styling on the frontend. That could be why you are having trouble. It's hard to say for sure. Through up a PR and I can take a closer look.

**Comment by OmgImAlexis** [comment]
I'll open a PR tomorrow morning but for now this helps.

With the site-media that's probably best to move to a REST route so the API is purely a REST API and nothing more. That would also allow for recipes to contain as many or as little amount of images as the user would like by just returning an array of images on a single route and then on another actually serve said images. You could even use this to allow the API to resize the images on the fly, add in watermarks, etc.  This shouldn't be too hard to do, I added something similar to a project I work on in about an hour.

I've moved the bootstrap to using npm instead of a CDN so everything is self contained and this prevents the site from breaking when there's no internet connection.

About the admin panel and rest GUI are they part of Django and are they part of the user app or mainly for developing? Maybe they can redone in React and moved to the frontend instead of shipping them with the API?

**Comment by RyanNoelk** [comment]
The admin panel is a part of Django and needed as of now. That is the main way of adding users to the app and also adding news items that are displayed on the homepage. Ideally we would create interfaces for those on the frontend. But I just haven't gotten the time to do that yet. 

The REST GUI is only needed for development. It basically allows the json to be send back in a pretty format.

As for the site-media, I 100% agree with you. Again, I just did it the quick way as a means to get the things to work.

**Comment by OmgImAlexis** [comment]
So for now the admin panel will need to be fixed on my end but it looks like the REST GUI can be removed as the Postman chrome extension does exactly that as well as a LOT of extra stuff. That'll cut down on the extras and mean the API is closer to being just an API.

I'll see how much free time I have, I may be able to add in the site-media routes for you.

**Comment by RyanNoelk** [comment]
I took care of the issue with exposing ports. I also created three other issues to deal with the other prblems that are discussed here.
- https://github.com/RyanNoelk/OpenEats/issues/159
- https://github.com/RyanNoelk/OpenEats/issues/160
- https://github.com/RyanNoelk/OpenEats/issues/161
