### ISSUE TITLE
Recipe sidebar links don't work

### ISSUE THREAD

**Issue by hermzz** [RyanNoelk/OpenEats#74]
URL `recipe_id` changes, but the content doesn't.

**Comment by RyanNoelk** [comment]
Looks like the DOM isn't reloaded in react-router if you just change the id of the route. See the following issues for more info.
- https://github.com/ReactTraining/react-router/issues/292
- https://github.com/ReactTraining/react-router/issues/97

**Comment by RyanNoelk** [comment]
Fixed with #76
