### ISSUE TITLE
Add support for fractions in the Recipe View and Recipe Form

### ISSUE THREAD

**Issue by RyanNoelk** [RyanNoelk/OpenEats#86]
When a recipe calls for a fraction (IE: 1/3 cup Flour) that needs to be expressed as a decimal (IE 0.333 cup Flour). We should support users entering in fractions and display them properly as well.

**Comment by hermzz** [comment]
How do you plan on displaying 1/3 rather than 0.333? Assuming we want to keep the numerical value of each quantity.

**Comment by RyanNoelk** [comment]
Yes we would keep the numerical value of 0.333 in the DB

There are some good libraries that we can use to get the fractions displaying better on the recipe view.(http://mathjs.org/docs/datatypes/fractions.html) But allowing users to create recipes with fractions will be another challenge.

**Comment by RyanNoelk** [comment]
Im going to unassign myself for this right now. Not 100% how I want to go about doing this.
