### ISSUE TITLE
Find a new logo

### ISSUE THREAD

**Issue by hermzz** [RyanNoelk/OpenEats#92]
I don't think it's appropriate for us to be using the logo from another project. [Flaticon](http://www.flaticon.com/icon-packs/cook) has a bunch of potential options worth looking at:

http://www.flaticon.com/packs/kitchen-8
http://www.flaticon.com/packs/kitchenware-2

**Comment by RyanNoelk** [comment]
100% agree. I'll start shopping around as well to see if I can find something. Let me know if you find a few you like.

**Comment by hermzz** [comment]
One pack I like is the [kitchen 14](http://www.flaticon.com/packs/kitchen-14) one. The [chef](http://www.flaticon.com/free-icon/chef_289645) would make a good logo, and we could use a few of the dish icons ([1](http://www.flaticon.com/free-icon/steak_289637), [2](http://www.flaticon.com/free-icon/pizza_289662), [3](http://www.flaticon.com/free-icon/fish_289650), [4](http://www.flaticon.com/free-icon/fried-eggs_289651), and [5](http://www.flaticon.com/free-icon/soup_289674)) as placeholders (ie: generate 5 placeholders and pick a random one every time we need to display a placeholder. We could also use the [chef hat](http://www.flaticon.com/free-icon/chef-hat_289644) or [cutlery](http://www.flaticon.com/free-icon/cutlery_289649).

**Comment by hermzz** [comment]
![9309bac5-e6d7-44e3-b77e-37ac514a62bd](https://cloud.githubusercontent.com/assets/129883/23175083/471a52a6-f856-11e6-92ad-77c047340aa8.png)

Thoughts, @RyanNoelk?

**Comment by RyanNoelk** [comment]
Thats amazing! Thanks for the awesome work!

**Comment by hermzz** [comment]
Cool! I've got some details to iron out and then I'll make a PR.
