### ISSUE TITLE
Redesign recipe layout

### ISSUE THREAD

**Issue by hermzz** [RyanNoelk/OpenEats#95]
Specifically the image bit, will create and upload some mocks later.

**Comment by hermzz** [comment]
A) Just remove the duplicate header and image, leave the thumb:
![6bab77fa-ef6b-4e78-8ca6-fc7b5c19c763](https://cloud.githubusercontent.com/assets/129883/22430127/ff12f4d4-e704-11e6-91a6-caca9e4d4907.png)

B) Remove thumbnail and stick the large image inside the panel:

![428ac4e9-8368-46ca-bf49-080a6344cc54](https://cloud.githubusercontent.com/assets/129883/22430129/ff2c8dd6-e704-11e6-8328-e9d8c84f181b.png)

C) Put the large image inside the header:

![6dd60950-1b77-4e98-ac9f-e461a3abecff](https://cloud.githubusercontent.com/assets/129883/22430128/ff2781a6-e704-11e6-9e73-d9be70b70d0a.png)

In my opinion C > B > A.

@RyanNoelk thoughts?

**Comment by RyanNoelk** [comment]
I do like B and C way more than A (leaning more to C). There are two things that bug me a little.
- The green text on title in image C can probable be change to a dark grey.
- The rating stars seem lonely and out of place where they are at right now. Many we can add it to the header? Not too sure how good that would look. I'll think about it for a bit and comment here if I have any more ideas.

**Comment by hermzz** [comment]
Regarding the header text in C, yeah, it's a quick mock I'd definitely try to make it a bit more readable.
As for the ratings, we could add them after the title if we make the stars a bit smaller?

**Comment by RyanNoelk** [comment]
That sounds good to me ^^

**Comment by RyanNoelk** [comment]
After some thought, one thing that I did like about the current design was that I was able to see the complete recipe (picture, ingredients, directions) all in one screen. I know it may be some work, but what are your thoughts about minimizing the recipe image as the user scrolls down the page to view the directions? 

Also one thing that we should keep in mind is how this is going to look on mobile. We'll need to make sure it scales well. Currently it has a design very similar to mock B.

**Comment by hermzz** [comment]
I've improved the layout a bit, moved the stars to the title, made the header text darker and the background white less transparent. Will probably add a bit more spacing between the header and the text. I feel this works a lot better and compresses the content more.

![ae944e25-040c-437c-9bfe-e9f74d1ef913](https://cloud.githubusercontent.com/assets/129883/22471956/0735397a-e7cc-11e6-9164-930099371a93.png)

The new layout works particularly well with the mobile version. When working on a recipe from my phone my main priority is to be able to see both the ingredient list and directions quickly, having them right next to each other is great: 

![5f1284d0-f5fa-4076-a090-8b1134132d4a](https://cloud.githubusercontent.com/assets/129883/22471957/0738414c-e7cc-11e6-9d1c-de16dafeee4c.png)

**Comment by RyanNoelk** [comment]
I'm liking the look a lot. The only thing I dislike is the desktop Ingredient position. I think we should swap that with the Cooking time, Prep, time, and servings info. 

I'm also thinking we can drop the recipe description from this page. After work I'll create a mock based on my comments so my ideas are more clear.

**Comment by hermzz** [comment]
What, have the ingredient list left and the cooking info on the right? Can be done, although not sure how to make that work in the mobile and still have the ingredients and directions together.

As for the description, I'd rather keep it, they can add context or tips for the recipe that wouldn't be in the directions part.

**Comment by RyanNoelk** [comment]
To move things around in mobile we can use the push and pull methods in bootstrap. We are using in now actually to move up the image thumbnail on mobile: 

https://github.com/RyanNoelk/OpenEats/blob/master/frontend/modules/recipe/components/Recipe.js#L161-L184

I also created a couple mocks, let me know what you think.

![0735397a-e7cc-11e6-9164-930099371a93](https://cloud.githubusercontent.com/assets/11916338/22492613/a2ebb7d2-e7f8-11e6-8d1e-71c170355603.png)

![0735397a-e7cc-11e6-9164-930099371a93](https://cloud.githubusercontent.com/assets/11916338/22492744/7df6fd6e-e7f9-11e6-9e9b-178b262e7ad4.png)

**Comment by hermzz** [comment]
I like the first one, the second one is nice and compact but I think it affects readability and having the description/details at the bottom looks weird. I think the first one is a good compromise between compactness and readability. Also, I think we should look at styling the description/details box a bit to make it a bit more obvious it's not part of the recipe.

**Comment by hermzz** [comment]
I've implemented a bunch of the changes (see hermzz/OpenEats@dad9cb55060e61baedff6d6a87c6f9fe08a32915) and I think it's looking good. There's one last thing on small screens that I want to fix, the title overlay becomes to big compared to the image. I'm going to make it so either in `sm` or `xs` the title stops being an overlay and just lies under the image without overlapping.
